name: Update SDKs

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - README.md
      - LICENSE
      - .github/CODEOWNERS

permissions:
  contents: read

concurrency:
  group: ci-sdk-automation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-per-service:
    strategy:
      fail-fast: false
      matrix:
        project: [ java ]
        service: [ checkout ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Clone ${{ matrix.project }} repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
          repository: Adyen/adyen-${{ matrix.project }}-api-library
          path: ${{ matrix.project }}/repo
          ref: fix/java-format-in-ci # Branch with composite action for testing

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Override properties
        if: matrix.project == 'java'
        env:
          PROJECT: ${{ matrix.project }}
        run: cp $PROJECT/gradle.properties buildSrc

      - name: Generate code for ${{ matrix.service }} in ${{ matrix.project }}
        env:
          PROJECT: ${{ matrix.project }}
          SERVICE: ${{ matrix.service }}
        run: ./gradlew $PROJECT:$SERVICE

      - name: Get OpenAPI commit SHA
        id: vars
        run: |
          echo "sha=$(cd schema && git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          echo "sha_short=$(cd schema && git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Check for and prepare formatting action
        id: prep_action
        run: |
          if [[ -f "${{ matrix.project }}/repo/.github/actions/format/action.yml" ]]; then
            echo "action_exists=true" >> "$GITHUB_OUTPUT"
            mkdir -p ./.temp-format-action
            mv "${{ matrix.project }}/repo/.github/actions/format" ./.temp-format-action/
          else
            echo "action_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Format Code
        if: steps.prep_action.outputs.action_exists == 'true'
        uses: ./.temp-format-action/format
        with:
          path: ${{ matrix.project }}/repo

      - name: Check for changes
        id: changes
        working-directory: ${{ matrix.project }}/repo
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          path: ${{ matrix.project }}/repo
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
          committer: ${{ secrets.ADYEN_AUTOMATION_BOT_TEST_EMAIL }}
          author: ${{ secrets.ADYEN_AUTOMATION_BOT_TEST_EMAIL }}
          branch: test-format-ci/${{ matrix.service }}
          title: '[TEST] [${{ matrix.service }}] Code generation: update services and models'
          body: |
            This PR contains the automated changes for the `${{ matrix.service }}` service.

            The commit history of this PR reflects the `adyen-openapi` commits that have been applied.
          commit-message: '[${{ matrix.service }}] Automated update from Adyen/adyen-openapi@${{ steps.vars.outputs.sha_short }}'
          labels: "automated pr"